// Code generated by goctl. DO NOT EDIT.
// Source: group.proto

package groupclient

import (
	"context"

	"goChat/app/group/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequest             = __.AddFriendRequest
	AddFriendResponse            = __.AddFriendResponse
	GroupUserListRequest         = __.GroupUserListRequest
	GroupUserListResponse        = __.GroupUserListResponse
	HandleFriendRequest          = __.HandleFriendRequest
	HandleFriendResponse         = __.HandleFriendResponse
	MessageGroupInfo             = __.MessageGroupInfo
	MessageGroupInfoListRequest  = __.MessageGroupInfoListRequest
	MessageGroupInfoListResponse = __.MessageGroupInfoListResponse
	MessageGroupInfo_ChatMsg     = __.MessageGroupInfo_ChatMsg
	UserGroupListRequest         = __.UserGroupListRequest
	UserGroupListResponse        = __.UserGroupListResponse

	GroupClient interface {
		AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
		HandleFriend(ctx context.Context, in *HandleFriendRequest, opts ...grpc.CallOption) (*HandleFriendResponse, error)
		GroupUserList(ctx context.Context, in *GroupUserListRequest, opts ...grpc.CallOption) (*GroupUserListResponse, error)
		UserGroupList(ctx context.Context, in *UserGroupListRequest, opts ...grpc.CallOption) (*UserGroupListResponse, error)
		MessageGroupInfoList(ctx context.Context, in *MessageGroupInfoListRequest, opts ...grpc.CallOption) (*MessageGroupInfoListResponse, error)
	}

	defaultGroupClient struct {
		cli zrpc.Client
	}
)

func NewGroupClient(cli zrpc.Client) GroupClient {
	return &defaultGroupClient{
		cli: cli,
	}
}

func (m *defaultGroupClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	client := __.NewGroupClientClient(m.cli.Conn())
	return client.AddFriend(ctx, in, opts...)
}

func (m *defaultGroupClient) HandleFriend(ctx context.Context, in *HandleFriendRequest, opts ...grpc.CallOption) (*HandleFriendResponse, error) {
	client := __.NewGroupClientClient(m.cli.Conn())
	return client.HandleFriend(ctx, in, opts...)
}

func (m *defaultGroupClient) GroupUserList(ctx context.Context, in *GroupUserListRequest, opts ...grpc.CallOption) (*GroupUserListResponse, error) {
	client := __.NewGroupClientClient(m.cli.Conn())
	return client.GroupUserList(ctx, in, opts...)
}

func (m *defaultGroupClient) UserGroupList(ctx context.Context, in *UserGroupListRequest, opts ...grpc.CallOption) (*UserGroupListResponse, error) {
	client := __.NewGroupClientClient(m.cli.Conn())
	return client.UserGroupList(ctx, in, opts...)
}

func (m *defaultGroupClient) MessageGroupInfoList(ctx context.Context, in *MessageGroupInfoListRequest, opts ...grpc.CallOption) (*MessageGroupInfoListResponse, error) {
	client := __.NewGroupClientClient(m.cli.Conn())
	return client.MessageGroupInfoList(ctx, in, opts...)
}
