// Code generated by goctl. DO NOT EDIT.
// Source: group.proto

package server

import (
	"context"

	"goChat/app/group/rpc/internal/logic"
	"goChat/app/group/rpc/internal/svc"
	"goChat/app/group/rpc/pb"
)

type GroupClientServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedGroupClientServer
}

func NewGroupClientServer(svcCtx *svc.ServiceContext) *GroupClientServer {
	return &GroupClientServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupClientServer) AddFriend(ctx context.Context, in *__.AddFriendRequest) (*__.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *GroupClientServer) HandleFriend(ctx context.Context, in *__.HandleFriendRequest) (*__.HandleFriendResponse, error) {
	l := logic.NewHandleFriendLogic(ctx, s.svcCtx)
	return l.HandleFriend(in)
}

func (s *GroupClientServer) GroupUserList(ctx context.Context, in *__.GroupUserListRequest) (*__.GroupUserListResponse, error) {
	l := logic.NewGroupUserListLogic(ctx, s.svcCtx)
	return l.GroupUserList(in)
}

func (s *GroupClientServer) UserGroupList(ctx context.Context, in *__.UserGroupListRequest) (*__.UserGroupListResponse, error) {
	l := logic.NewUserGroupListLogic(ctx, s.svcCtx)
	return l.UserGroupList(in)
}

func (s *GroupClientServer) MessageGroupInfoList(ctx context.Context, in *__.MessageGroupInfoListRequest) (*__.MessageGroupInfoListResponse, error) {
	l := logic.NewMessageGroupInfoListLogic(ctx, s.svcCtx)
	return l.MessageGroupInfoList(in)
}
