// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"goChat/app/user/rpc/internal/logic"
	"goChat/app/user/rpc/internal/svc"
	"goChat/app/user/rpc/pb"
)

type UserClientServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserClientServer
}

func NewUserClientServer(svcCtx *svc.ServiceContext) *UserClientServer {
	return &UserClientServer{
		svcCtx: svcCtx,
	}
}

func (s *UserClientServer) Login(ctx context.Context, in *__.LoginRequest) (*__.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserClientServer) Register(ctx context.Context, in *__.RegisterRequest) (*__.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserClientServer) PersonalInfo(ctx context.Context, in *__.PersonalInfoRequest) (*__.PersonalInfoResponse, error) {
	l := logic.NewPersonalInfoLogic(ctx, s.svcCtx)
	return l.PersonalInfo(in)
}
