// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package server

import (
	"context"

	"goChat/app/msg/rpc/internal/logic"
	"goChat/app/msg/rpc/internal/svc"
	"goChat/app/msg/rpc/pb"
)

type MessageClientServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedMessageClientServer
}

func NewMessageClientServer(svcCtx *svc.ServiceContext) *MessageClientServer {
	return &MessageClientServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageClientServer) Upload(ctx context.Context, in *__.UploadRequest) (*__.UploadResponse, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

func (s *MessageClientServer) Pull(ctx context.Context, in *__.PullRequest) (*__.PullResponse, error) {
	l := logic.NewPullLogic(ctx, s.svcCtx)
	return l.Pull(in)
}
